# Generated by Django 3.0.2 on 2020-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200308_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Carbs'), ('P', 'Proteins'), ('F', 'Fats')], max_length=2),
        ),
    ]
